Revert "Don't check documentation completeness in this stable branch"
This reverts commit 0273bfb815ef74115d614f5e5f04e013374f7a01.

diff --git a/docs/reference/Makefile.am b/docs/reference/Makefile.am
--- a/docs/reference/Makefile.am
+++ b/docs/reference/Makefile.am
@@ -142,6 +142,14 @@ check-local:
 			echo "$$file missing from telepathy-glib-docs.sgml"; \
 			err=1; \
 		fi; \
-	done
+	done; \
+	case $(enable_fatal_warnings)/$$err in \
+		(yes/1) \
+			echo "Documentation check failed" >&2; \
+			exit $$err; \
+			;; \
+		(*) \
+			exit 0; \
+			;; \
+	esac
 endif
-# ... but don't fail on incomplete documentation, this is a stable branch
